intel/tdx-tools

.github/workflows/pr-check.yml, .gitignore, README.md, start-qemu.sh
=> Add start_qemu.sh to create TD guest via qemu-kvm command

build/centos-stream-8/pkg-builder/README.md
1. Introduce how to create the container for pkg-builder which allow the tools running from any Linux OS or github action
2. Introduce how to use pkg-builder container build individual package
3. Introduce how to use it in github action
=> Add introduction for pkg-builder

build/.gitignore, build/centos-stream-8/build-repo.sh
1. Build individual RPM packages via build.sh in each component's subdirectory
2. Create host and guest repo in seperated directory
3. Use createrepo to create meta
=> Add script to build RPM repo for CentOS Stream 8.

.github/workflows/pr-check.yml, .pylintrc, utils/pycloudstack/.gitignore, utils/pycloudstack/.pylintrc, utils/pycloudstack/README.md, utils/pycloudstack/pycloudstack/artifacts.py, utils/pycloudstack/pycloudstack/cmdrunner.py, utils/pycloudstack/pycloudstack/dut.py, utils/pycloudstack/pycloudstack/msr.py, utils/pycloudstack/pycloudstack/templates/legacy-base.xml, utils/pycloudstack/pycloudstack/templates/ovmf-base.xml, utils/pycloudstack/pycloudstack/templates/sgx-base.xml, utils/pycloudstack/pycloudstack/templates/tdx-base.xml, utils/pycloudstack/pycloudstack/virtxml.py, utils/pycloudstack/pycloudstack/vmguest.py, utils/pycloudstack/pycloudstack/vmimg.py, utils/pycloudstack/pycloudstack/vmm.py, utils/pycloudstack/pycloudstack/vmparam.py, utils/pycloudstack/requirements.txt, utils/pycloudstack/setup.py
pycloudstack is a python library to abstract common operations in
hypervisor/kvm or kubernetes based cloud stack. It can be used to
create test, deployment and automation tool for specifc cloud stack
like SGX/TDX/AMX etc.
=> Add python library pycloudstack

build/centos-stream-8/guest-image/kickstart/centos-stream.ks, build/centos-stream-8/guest-image/tdx-guest-stack.sh
Support podman and docker commands, but no docker service
=> Install podman-docker in guest-image

README.md, doc/run_tests.md
Add document of how to run tests.
=> Add test doc

README.md
=> README.md: add manual build and install instructions

README.md, start-qemu.sh
/start-qemu.sh --help will call Usage() 6 times.
The script should exit after print usage
=> refine help function of start-qemu.sh

start-qemu.sh
There are two ways to run quote generation in TD:
1. Get quote with vsock
2. Get quote with tdvmcall
This patch allows user to specify quote generation type via an additional
optional argument 'q':
-q vsock
-q tdvmcall
When requesting a quote via 'vsock', 'vsock' is enabled and the kernel command
line will contain 'tdx_disable_filter'. (User is still responsible for the creation
of the required file /etc/tdx-attest.conf in TD VM needed in this case.)
When requesting a quote via 'tdvmcall', the qemu command line
'-object tdx-guest,id=tdx'
is modified to
'-object tdx-guest,id=tdx,quote-generation-service=vsock:2:4050'
Examples:
./start-qemu.sh -i td-guest-rhel-8.5.qcow2 -k vmlinuz-rhel-8.5 -q vsock
./start-qemu.sh -i td-guest-rhel-8.5.qcow2 -k vmlinuz-rhel-8.5 -q tdvmcall
Signed-off-by: …
=> start-qemu.sh: add support for TD quote generation

start-qemu.sh
The number of CPUs and sockets is presently hardcoded as 1 each.
To change any of these values, user needs to edit the shell script.
This patch adds support to pass the desired number of cores and sockets via
command line options. The default values remain as before.
Number of CPUs must be positive, no upper limit checks. The assumption here
is that the user knows what he/she is doing.
Number of sockets is limited to reasonable values of 1 or 2.
Both limits can be easily modified if needed.
Note we use the upper case letter 'S' to specify the number of sockets,
as the lower case letter 's' is used to specify serial terminal.
Example: Create VM with 16 CPU cores and 2 sockets (8 CPUs per socket):
./start-qemu.sh -i td-guest-rhel8.5.qcow2 -k vmlinuz-rhel8.5 -c 16 -S 2
The CPU topology can …
=> start-qemu.sh: allow to specify number of CPUs and sockets via cmdline

doc/secure_boot.md
Will be clearer if using it outside this repository.
=> secureboot: add link to tdvfkeyenroll

CONTRIBUTING.md, README.md, build/centos-stream-8/intel-mvp-tdx-guest-grub2/README.md, build/centos-stream-8/intel-mvp-tdx-guest-shim/README.md, build/centos-stream-8/intel-mvp-tdx-libvirt/README.md, build/centos-stream-8/intel-mvp-tdx-tdvf/README.md, build/rhel-8/intel-mvp-tdx-guest-grub2/README.md, build/rhel-8/intel-mvp-tdx-guest-shim/README.md, build/rhel-8/intel-mvp-tdx-libvirt/README.md, build/rhel-8/intel-mvp-tdx-tdvf/README.md, doc/create_guest_image.md, doc/launch_td_guest.md, doc/run_tests.md, doc/secure_boot.md, utils/pytdxmeasure/README.md
=> doc: Fix markdown lint issues.

doc/verify_tdx_host.md
=> verify_tdx_host.md: Refine the wording for MK-TME key verification

doc/launch_td_guest.md, doc/run_tests.md, doc/verify_tdx_host.md, tests/artifacts.yaml.template, tests/run.sh
These were pushed to the 2022ww14 branch but should have been targetted at the main branch.
@ruomengh When rebasing I needed to fix one conflict with the main branch in commit [doc/run_tests.md: add usage instruction of -g](https://github.com/intel/tdx-tools/commit/995643e5ecace1173d1a9b69d737457a49a8bea4). I also fixed some spelling/grammar issues in the final commit of the PR. Please make sure these changes still match your intentions.
=> Ruomeng fixes

doc/launch_td_guest.md
=> doc/lauch_td_guest.md: change to spr kernel

build/centos-stream-8/README.md, doc/create_guest_image.md, doc/launch_td_guest.md, doc/verify_tdx_host.md
Fix several markdown issues.
Also slightly improve grammar in some areas.
=> Fix markdown issues

README.md
=> README.md: Add reference for measured and secure boot in BKM.

start-qemu.sh
=> start-qemu.sh: support qcow2 and img format for disk image

.github/workflows/pr-test-build-centos-stream-8-kernel.yml
=> intel-mvp-spr-kernel: Fix broken path for CentOS Stream's git action

utils/pycloudstack/pycloudstack/templates/tdx-base.xml
=> pycloudstack: disable memballoon since TDX not support it

doc/create_guest_image.md
=> Doc/create_guest_image.md:Remove content of Ubuntu from guest image doc

doc/launch_td_guest.md
The script name needs to update from start_qemu.sh to start-qemu.sh
=> launch_td_guest.md: update start_qemu.sh to start-qemu.sh

build/ubuntu-22.04/build-guest-debs.sh, build/ubuntu-22.04/guest-img/README.md, build/ubuntu-22.04/guest-img/tdx-guest-stack.sh
Leverage ubuntu official cloud image and customized with TDX guest stack.
=> ubuntu 22.04: build guest image for TDX

.github/workflows/pr-check.yml, .gitignore, .pylintrc, build/ubuntu-22.04/README.md, build/ubuntu-22.04/build-repo.sh, build/ubuntu-22.04/guest-image/tdx-guest-stack.sh, utils/pycloudstack/pycloudstack/virtxml.py, utils/pycloudstack/pycloudstack/vmm.py, utils/pytdxmeasure/pytdxmeasure/actor.py, utils/pytdxmeasure/pytdxmeasure/cli.py, utils/tdvfkeyenroll/tdvfkeyenroll/secure_boot.py
=> ubuntu-22.04: Refine the build script

doc/create_guest_image.md
=> create_guest_image.md: add link to ubuntu guest image

doc/create_guest_image.md
=> create_guest_image.md: Add Ubuntu to support list

build/rhel-8/intel-mvp-spr-qemu-kvm/spr-qemu.spec
=> qemu-kvm: disable build check for rhel

doc/developer_guide.md
=> developer-guide.md: Fix typo

doc/developer_guide.md
=> developer_guide: fix broken link when generating document

build/ubuntu-22.04/guest-image/tdx-guest-stack.sh
=> ubuntu 22.04: refine guest image tdx-guest-stack.sh

build/ubuntu-22.04/README.md, build/ubuntu-22.04/intel-mvp-spr-kernel/build.sh
=> ubuntu 22.04: add some comments and build requirements

build/ubuntu-22.04/intel-mvp-spr-kernel/build.sh, build/ubuntu-22.04/intel-mvp-tdx-guest-grub2/build.sh, build/ubuntu-22.04/intel-mvp-tdx-guest-shim/build.sh
=> ubuntu 22.04: add distro check to build scripts

build/ubuntu-22.04/guest-image/netplan.yaml
1. Use wildcard for net devices
2. Change DHCP identifier from machine-id to MAC address
=> ubuntu 22.04: update network configurations

build/ubuntu-22.04/README.md
Add instructions to build and install host debian packages.
=> ubuntu-22.04: add host steps in README.md

build/ubuntu-22.04/build-repo.sh
1. Remove grub2-build-deps-depends, grub2-unsigned-build-deps-depends after building grub
2. Running whole script as root is not allowed due to libvirt build failure
=> ubuntu 22.04: refine build-repo.sh

tests/requirements.txt
Add 2 requirements to make sure tests pass.
=> tests/requirements.txt - add requirements

tests/tests/test_tdx_host_status.py, utils/pycloudstack/pycloudstack/msr.py
Signed-off-by: HongyeX Qu <hongyex.qu@intel.com>
=> test: add more tests for TDX host status

.github/workflows/pr-check.yml, utils/bcc_trace_tdcall.py
=> utils: add example to use eBPF tracing TDCALL

.gitignore
=> clean gitignore

README.md, utils/pycloudstack/README.md
=> pycloudstack: Add more docs

.github/workflows/pr-test-build-centos-stream-8-kernel.yml, .github/workflows/pr-test-build-centos-stream-8.yml, README.md
=> README.md: Enable kernel build status

doc/launch_td_guest.md
XML template is provided via hyperlink, there is no need to keep xml file content in the doc.
Signed-off-by: Hao,Ruomeng <ruomeng.hao@intel.com>
=> doc/launch_td_guest.md: remove xml file

.github/workflows/pr-check.yml, README.md
=> doc: change the badge for CI checking

.github/workflows/pr-ubuntu-22.04-kernel.yml, build/ubuntu-22.04/intel-mvp-tdx-kernel/build.sh
=> build: Add CI for ubuntu kernel

utils/pycloudstack/pycloudstack/virtxml.py, utils/pycloudstack/pycloudstack/vmguest.py, utils/pycloudstack/pycloudstack/vmm.py
1. Support to add element to specific parent
2. Support to create VM with specific io cache mode
3. Support to create VM with multi disks
Signed-off-by: Hao,Ruomeng <ruomeng.hao@intel.com>
=> Customize xml

README.md, doc/create_guest_image.md, doc/secure_boot.md
1  remove centos build and install
2  change OVMF_VAR and OVMF_CODE to OVMF
3  add ubuntu guest secure boot steps
4  change libvirt xml for secure boot
=> doc : update secure boot , readme and create guest image

README.md, doc/secure_boot.md, doc/tdx_libvirt_direct.xml.template, doc/tdx_libvirt_grub.xml.template
1  update libvirt xml : direct and grub boot
2  update secure boot indents in sign key shim/grub/kernel
3  update README.md
=> doc : change indents in libvirt template xml

doc/tdx_libvirt_direct.ubuntu_host.xml.template, doc/tdx_libvirt_grub.ubuntu_host.xml.template
=> doc: update libvirt template for ubuntu host

doc/create_guest_image.md, doc/run_tests.md
1  remove centos information from run-tests.sh
2  remove ubuntu EFI guest image creating in create_guest_image.md
3  change ubuntu-22.04/README.md link 2022ww49 link
=> doc : remove centos contents and modify link

tests/run.sh
=> run.sh: fix wrong judgement for guest distro.

.github/workflows/pr-rhel-8-grub2.yml, .github/workflows/pr-rhel-8-kernel.yml, .github/workflows/pr-rhel-8-libvirt.yml, .github/workflows/pr-rhel-8-ovmf.yml, .github/workflows/pr-rhel-8-qemu-kvm.yml, .github/workflows/pr-rhel-8-shim.yml, build/rhel-8/intel-mvp-tdx-guest-grub2/build.sh
=> rhel-8: enable github action on self-hosted runner

utils/pytdxmeasure/pytdxmeasure/tdreport.py, utils/pytdxmeasure/setup.py
=> Update for the new TDREPORT structure introduced from kernel 5.19

utils/pycloudstack/pycloudstack/vmparam.py
=> vmparam.py: use OVMF.fd other than debug version

build/rhel-8/intel-mvp-ovmf/build.sh, build/rhel-8/intel-mvp-ovmf/ovmf.spec, build/ubuntu-22.04/intel-mvp-ovmf/build.sh, build/ubuntu-22.04/intel-mvp-ovmf/debian/changelog
=> build/ovmf: update to stable202211

build/rhel-8/README.md
=> build/rhel-8: add EPEL repo in README

.github/workflows/pr-check.yml
=> pr-check.yml: Add apt-get update

start-qemu.sh
=> start-qemu.sh: Fix typo of OVMF

start-qemu.sh
Signed-off-by: Dong, Xiaocheng <xiaocheng.dong@intel.com>
=> start-qemu.sh: Add QEMU and Kernel parameter for GDB debug

README.md
=> README.md: modify 2 URL links to refer to the latest information

tests/tests/test_max_cpu.py, tests/tests/test_tdvm_network.py
1. Add test for TDVM network functionality test
2. Add test for TDVM boot with large vCPU count
=> Add environment tests for TDX

doc/run_tests.md, tests/tests/nginx-bench.sh, tests/tests/test_workload_nginx.py
1. Add E2E workload test with nginx
2. Update run_tests.md to include preparation of running the test
=> Add test for workload

tests/tests/test_acpi_reboot.py, tests/tests/test_acpi_shutdown.py, tests/tests/test_vm_reboot_qga.py, tests/tests/test_vm_shutdown_mode.py, tests/tests/test_vm_shutdown_qga.py
1. Add reboot test using qemu guest agent
2. Add shutdown test using qemu guest agent
3. Add multiple shutdown mode test
4. Add acpi reboot test
5. Add acpi shutdown test
=> Add test for VM lifecycle

.github/workflows/pr-check.yml, attestation/pytdxmeasure/pytdxmeasure/cli.py, attestation/pytdxmeasure/pytdxmeasure/rtmr.py, attestation/pytdxmeasure/setup.py, attestation/pytdxmeasure/tdx_extend_rtmr
* Add extra function extend_rtmr to perform rtmr write
=> Pytdxmeasure: Add function for RTMR write

.pylintrc, attestation/pytdxmeasure/pytdxmeasure/tdreport.py, attestation/pytdxmeasure/pytdxmeasure/utility.py, utils/pycloudstack/.pylintrc, utils/pycloudstack/pycloudstack/vmparam.py
Refactor function TdReport.get_td_report
* Refactor struct tdx_report_req
* Refactor /dev/tdx_guest Operator TDX_CMD_GET_REPORT0
Update tdreport structure
* Append new field tee_tcb_info.tee_tcb_svn2: offset 128 bytes and size 16 bytes
* Append new field tdinfo.servtd_hash: offset 400 bytes and size 48 bytes
=> attestation/pytdxmeasure: update tdreport struct & device operation

doc/tdx_libvirt_direct.ubuntu_host.xml.template, doc/tdx_libvirt_direct.xml.template, doc/tdx_libvirt_grub.ubuntu_host.xml.template, doc/tdx_libvirt_grub.xml.template
Add memoryBacking entry for guest.
=> doc: update template for libvirt

build/rhel-8/build-repo.sh, build/ubuntu-22.04/build-repo.sh
Add support for RHEL 8.7 build environemnt.
Update to kernel v6.2, qemu 7.2.0.
=> build-repo: update to latest 6.2 stack

doc/secure_boot.md
* Update start_qemu.sh and templates links
* Update start_qemu.sh parameter
=> doc/secure_boot: fix bugs

attestation/pytdxmeasure/README.md
=> attestation/pytdxmeasure: update measure tool

utils/pycloudstack/pycloudstack/vmguest.py
Add parameters to support tsx/tsc/mwait configuration when TD boot
=> pycloudstack: add parameters for tsx/tsc/mwait

.github/workflows/pr-check.yml, doc/developer_guide.md
Update to kernel v6.2, qemu v7.2.0 and edk2-stable202302.
=> doc: update developer_guide.md

attestation/pytdxmeasure/pytdxmeasure/tdreport.py, attestation/pytdxmeasure/pytdxmeasure/utility.py, utils/td-migration/user-td.sh
parse and return the valid ModuleVersion
=> attestation/pytdxmeasure: parse module version

utils/pycloudstack/pycloudstack/virtxml.py, utils/pycloudstack/pycloudstack/vmm.py
These options will be configurable for TDVM.
=> pycloudstack: add options for tsc, tsx and mwait

.github/workflows/.aspell.en.pws, doc/enable_ima_with_tdx_rtmr.md
add a user guide to give brief introduction and detail configurations for IMA usage with RTMR.
=> Add user guide for IMA usage with TDX RTMR

build/rhel-8/guest-image/README.md, build/rhel-8/guest-image/tdx-guest-stack.sh, build/ubuntu-22.04/README.md, build/ubuntu-22.04/guest-image/README.md, build/ubuntu-22.04/guest-image/tdx-guest-stack.sh
Refer to build/<distro_type>/guest-image/README.md to build TDX guest image.
=> build: add README.md for creating guest image

build/ubuntu-22.04/build-repo.sh
In case of a build failure, re-running build-repo.sh can skip the same and continue the build where it failed.
=> build/ubuntu: improve build-repo.sh for incremental builds

utils/check-tdx-guest.sh
This script can be used to check the TDX status in guest.
=> Add check-tdx-guest.sh

.github/workflows/pr-ubuntu-22.04-build-repo.yml, build/ubuntu-22.04/README.md, build/ubuntu-22.04/build-repo.sh, build/ubuntu-22.04/docker-pkg-builder/Dockerfile, build/ubuntu-22.04/intel-mvp-tdx-libvirt/debian/rules, build/ubuntu-22.04/pkg-builder
Porting ubuntu container builder.
Add workflow to check buid all script build_repo.sh in docker container.
=> 5.19 forward

start-qemu.sh, utils/pycloudstack/pycloudstack/virtxml.py, utils/pycloudstack/pycloudstack/vmguest.py, utils/pycloudstack/pycloudstack/vmm.py
1. update start-qemu.sh to support hugepage_path in qemu command
2. update vmm.py, vmguest.py and virtxml.py to support hugepage_path in libvirt tests
=> Support UPM hugepage usage change

start-qemu.sh, utils/pycloudstack/pycloudstack/virtxml.py, utils/pycloudstack/pycloudstack/vmguest.py, utils/pycloudstack/pycloudstack/vmm.py
This reverts commit b688fcf0853b5cfc2cfa2f426ea66ba04d5e92d0.
i.e. reverts https://github.com/intel/tdx-tools/pull/337
=> Revert "Support UPM hugepage usage change (#337)"

utils/check-tdx-host.sh
=> fix typo and package name

build/ubuntu-22.04/guest-image/cloud-init-data/user-data.template, build/ubuntu-22.04/guest-image/create-ubuntu-image.sh
1. Originally, the script will only install kernel and grub/shim, since grub/shim need special instruction to avoid installation issue.
2. Add new dependencies like golang-go, golang, golang-doc in user-data.template.
3. Use dpkg -i *.deb to install all packages from the directory of guest_repo.
=> create-ubuntu-image.sh: Install all deb package from guest_repo.

utils/check-tdx-guest.sh
This change will resolve issue:
https://github.com/intel/tdx-tools/issues/342
=> check-tdx-guest.sh: add more check

build/ubuntu-22.04/intel-mvp-tdx-kernel/build.sh, build/ubuntu-22.04/intel-mvp-tdx-qemu-kvm/build.sh
Append default timezone info if the system timezone does not exist.
=> build/ubuntu: install tzdata based on the system timezone setting

start-qemu.sh
Guest image file format should be QCOW for qcow2 image
=> start-qemu.sh: fix guest image format issue

utils/td-migration/connect.sh, utils/td-migration/pre-mig.sh, utils/td-migration/user-td.sh
This is more flexible to support single migtd and multi user TDs.
Also add support for non-TD VM.
=> td-migration: parameterize more variables

utils/td-migration/README.md, utils/td-migration/mig-flow.sh, utils/td-migration/mig-td.sh, utils/td-migration/pre-mig.sh, utils/td-migration/user-td.sh
1. Support pre-binding
2. Support post-copy
3. Support multi-stream
=> utils/td-migration: Update scripts to support advanced feature

utils/td-migration/README.md, utils/td-migration/user-td.sh
Add new parameter to config migtd_attr.
=> td-migration: support custom migtd attribute

build/ubuntu-22.04/guest-image/create-ubuntu-image.sh
=> Fix error on creating guest image

utils/td-migration/mig-flow.sh, utils/td-migration/pre-mig.sh
- Fix the pre-mig bug that cannot get dest migtd pid in the cross host scenario.
- Support post-copy and multifd in cross host case.
=> td-migration: support post-copy and multifd in cross host case

build/ubuntu-22.04/build-repo.sh
Reported-by: Benny Fuhry <benny.fuhry@intel.com>
=> build/ubuntu: Fix wrong logic for GUEST_ONLY

tests/README.md
=> tests/README.md: fix broken link

utils/pycloudstack/pycloudstack/cluster.py, utils/pycloudstack/pycloudstack/vmguest.py, utils/pycloudstack/pycloudstack/vmm.py
1. cluster.py: add KubeVirtCluster to manipulate kubevirt CRDs.
2. vmm.py: align with VMMLibvirt, add VMMKubeVirt to control the lifecycle of td-guest.
3. vmguest.py: support to create kuvirt td-guest.
=> pycloudstack: Add new VMM VMMKubeVirt to manage kubevirt td-guest

build/ubuntu-22.04/intel-mvp-tdx-kernel/build.sh, build/ubuntu-22.04/intel-mvp-tdx-qemu-kvm/build.sh
Append default timezone info if the system timezone does not exist.
=> build/ubuntu: install tzdata based on the system timezone setting (#362)

start-qemu.sh
Add parameter "-u" to accept huegpage mount point and enable hugepage for TD
=> start-qemu.sh: support hugepage setting for TD

.github/workflows/.aspell.en.pws, build/ubuntu-22.04/vmware/README.md
Initial directory to build vmware ESXi specific TDVM for ubuntu.
=> vmware: create initial build directory for vmware

utils/check-tdx-host.sh
Cherry-pick the commits from main to tdx-1.0.
Now the check-tdx-host.sh is same as main.
=> check-tdx-host.sh: cherry-pick from main to tdx-1.0

utils/check-tdx-host.sh
Cherry-pick the commits from main to tdx-1.5.
Now the check-tdx-host.sh is same as main.
=> check-tdx-host.sh: cherry-pick from main to tdx-1.5

.gitignore, build/ubuntu-22.04/docker-pkg-builder/Dockerfile, build/ubuntu-22.04/intel-mvp-tdx-migration/build.sh
- Update tag
- Update rust dependencies
- Move rust installation to dockerfile
=> build/ubuntu-22.04: update tdx-migration build

build/ubuntu-22.04/intel-mvp-vtpm-td/build.sh, build/ubuntu-22.04/intel-mvp-vtpm-td/debian/changelog, build/ubuntu-22.04/intel-mvp-vtpm-td/debian/rules
Rust toolchain upgraded to nightly-2023-08-28.
=> ubuntu-22.04: update vtpm-td v0.2.1

utils/check-tdx-host.sh
Also add more info in the corresponding comment.
=> check-tdx-host.sh: fix typo

.github/workflows/pr-check-document.yml, .github/workflows/pr-check-license.yml, .github/workflows/pr-check-python.yml, .github/workflows/pr-check-shell.yml, .github/workflows/pr-fde.yml, .github/workflows/publish-pycloudstack.yml, .github/workflows/publish-pytdxmeasure.yml
Fix OpenSSF warning: no topLevel permission defined.
=> workflow: define read-all permission for all of the scopes

.github/workflows/.aspell.en.pws, README.md
Refer to mid-stream distros for TDX enablement.
=> README: Add SW information
