- build/centos-stream-8/intel-mvp-tdx-guest-grub2/README.md
- build/centos-stream-8/intel-mvp-tdx-guest-grub2/build.sh
- build/centos-stream-8/intel-mvp-tdx-guest-grub2/grub.macros
- build/centos-stream-8/intel-mvp-tdx-guest-grub2/tdx-guest-grub2.spec
Used to build grub 2.02 RPMs on centos stream8.
Usage: ./build.sh
The downstream patchset will also be generated.
> build for intel-mvp-tdx-guest-grub2

- build/centos-stream-8/intel-mvp-tdx-guest-shim/README.md
- build/centos-stream-8/intel-mvp-tdx-guest-shim/build.sh
- build/centos-stream-8/intel-mvp-tdx-guest-shim/tdx-guest-shim.spec
Used to build shim RPMs on centos stream8.
Usage: ./build.sh
> build for intel-mvp-tdx-guest-grub2 based on upstream shim-15.4

- .github/workflows/pr-check.yml
- .github/workflows/pr-test-build-centos-stream-8.yml
- build/centos-stream-8/pkg-builder/Dockerfile
- build/centos-stream-8/pkg-builder/action.yml
- build/centos-stream-8/pkg-builder/aliyun.repo
- build/centos-stream-8/pkg-builder/entrypoint.sh
1. Add github action pkg-builder for CentOS Stream 8.
2. Use aliyun mirror for CentOS Stream's BaseOS, PowerTools and AppStream.
3. Enable github action to build testing for grub and shim.
> Enable github action for building packages for CentOS Stream 8

- .github/workflows/pr-test-build-centos-stream-8.yml
- build/.gitignore
- build/centos-stream-8/intel-mvp-tdx-tdvf/README.md
- build/centos-stream-8/intel-mvp-tdx-tdvf/build.sh
- build/centos-stream-8/intel-mvp-tdx-tdvf/tdvf.spec
1. TDVF provide EFI BIOS for TD guest, it bases on OVMF.
2. TDVF spec https://software.intel.com/content/dam/develop/external/us/en/documents/tdx-virtual-firmware-design-guide-rev-1.pdf
3. Current implementation supports:
- Lazy Page Accept
- RTMR based measured boot
- Secure boot
- EFI handover approach for qemu direct and grub boot
> Add package build for TDVF(Trusted Domain Virtual Firmware) component

- .github/workflows/pr-test-build-centos-stream-8.yml
- build/centos-stream-8/intel-mvp-tdx-qemu-kvm/README.md
- build/centos-stream-8/intel-mvp-tdx-qemu-kvm/build.sh
- build/centos-stream-8/intel-mvp-tdx-qemu-kvm/tdx-qemu.spec
1. The pre-integration repo for qemu-kvm is at https://github.com/intel/qemu-tdx.git
2. Current implementation supports:
- confidential-guest-support for tdx
- "debug=on" to do off-TD debugging for TD VM
- load TDVF via "-device loader" instead of pflash
> Add package build for TDX qemu-kvm

- .github/workflows/pr-test-build-centos-stream-8.yml
- build/centos-stream-8/intel-mvp-tdx-libvirt/README.md
- build/centos-stream-8/intel-mvp-tdx-libvirt/build.sh
- build/centos-stream-8/intel-mvp-tdx-libvirt/tdx-libvirt.spec
1. Upstream libvirt need to be modified for TDX VM like type of <launchSecurity>, OVMF loader etc.
2. Current implementation support:
- mrOwner hash for launch security
- Secure boot for TD VM
- hard reboot via virsh for TD VM
> Add package build for TDX libvirt

- build/centos-stream-8/intel-mvp-tdx-guest-grub2/grub.macros
- build/centos-stream-8/intel-mvp-tdx-guest-grub2/tdx-guest-grub2.spec
Obsolete grub2-pc, grub2-tools-minimal, grub2-tools-extra.
Enable legacy grub2-pc-modules.
Signed-off-by: Jialei Feng <jialei.feng@intel.com>
> Resolve conflicts and obsoletes

- build/centos-stream-8/intel-mvp-tdx-host-kernel/tdx-host-kernel.spec
We don't publish a tdx-module package yet. Remove this dependency so
that the host kernel can at least be installed, even though TDX will
not be available without the module.
> tdx-host-kernel.spec: remove dependency on tdx-module package

- utils/pytdxmeasure/setup.py
add file entension to tdx_eventlogs, tdx_tdreport, tdx_verify_rtmr
> remove .sh extension from setup.py for tdx_eventlog, tdx_tdreport, tdx_verify_rtmr

- build/centos-stream-8/intel-mvp-tdx-qemu-kvm/build.sh
Fetch RPM sources directly in RPM spec.
Remove unused qemu-kvm-2.12.0-88.module_el8.1.0+266+ba744077.2.src
downloaded from https://vault.centos.org/8.1.1911
> qemu-kvm: fetch sources from https://git.centos.org/rpms/qemu-kvm

- build/centos-stream-8/guest-image/tdx-guest-stack.sh
Add --repo to avoid refreshing metadata for all repository.
So TDX stack can be installed from the local repository without internet access.
> guest-image: specify local repository when installing TDX packages

- build/centos-stream-8/intel-mvp-tdx-guest-grub2/build.sh
rhel-8.4 has been changed to rhel-8.4.0 in https://github.com/rhboot/grub2.git
> upstream branch changed from rhel-8.4 to rhel-8.4.0

- build/centos-stream-8/intel-mvp-tdx-guest-grub2/build.sh
- build/centos-stream-8/intel-mvp-tdx-guest-grub2/tdx-guest-grub2.spec
- build/centos-stream-8/intel-mvp-tdx-guest-shim/build.sh
Make grub and shim build tools more robust.
There are several new commits recently(03/09) in upstream branch, so the
base commit has changed. Refer to https://github.com/rhboot/grub2/
> Use downstream tag and pin upstream base commit for grub and shim

- start-qemu.sh
Do not automatically exit with an error 1 after the 'usage'
screen is displayed. This prevents displying any additional
error messages that are meant to eventually follow.
Exit with an error when an invalid argument is specified,
display the invalid argument as well.
> start-qemu.sh: fix 'usage' handling

- start-qemu.sh
- utils/pycloudstack/pycloudstack/vmguest.py
TD guest kernel only allow limited device/driver via device filter approach
due to security consideration. So
1. By default, tdx_disable_filter should be removed from guest kernel command
2. vsock in guest is disabled by default via filter, so if want get TDREPORT
via vsock approach instead of from TDVMCALL, tdx_disable_filter is a
workaround to use.
3. Remove unnecessary disabling for pylint.
> Clean up tdx_disable_filter flag for security consideration

- utils/pycloudstack/pycloudstack/vmm.py
SSH port forward is used to map guest SSH port to local host without
bridge networking. But this approach might cause unpredicted boot
duration. So disable it by default for fast boot.
> Not enable SSH port forward by default

- tests/tests/conftest.py
- tests/tests/test_tdvm_tsc.py
- tests/tests/test_tdx_guest_status.py
1. Disable redefined-outer-name warning since it is false positive for pytest's fixture approach
2. Convert the CRLF style => LF style for conftest.py
> Fix pylint issues for test modules

- utils/pycloudstack/cluster.py
- utils/pycloudstack/registry.py
Docker based container or Kubernetes cluster are typical ochrestrator
for cloud computing in data center, so
1. Add registry.py class to manage the pull and run container from given
registry
2. Add cluster.py class to create/deploy pod/job on a Kubernetes cluster
> Add operator classes for container registry and kubernete cluster

- doc/secure_boot.md
Introdcue the steps to enable secure boot in a td guest.
The guide uses utils/tdvf-key-enroll in this repo.
> add secure boot guide for tdx

- .github/workflows/pr-check.yml
- utils/pycloudstack/requirements.txt
1. When pylint found any known issues on python module, CI should
report the error to committer for fix before review. But current CI
script in github action will ignore issues.
2. Before pylint scan the python module, the CI need install all
dependencies and configure the PYTHONPATH well.
> CI: fix the code scan issue of ignoring pylint errors

- CONTRIBUTING.md
Add initial CONTRIBUTING.md file. For now it only includes commit
style guidelines, but in the future may include other additions such
as pull request guidelines, issue reporting guidelines and others.
> tdx-tools: add CONTRIBUTING.md for commit style guidelines

- build/centos-stream-8/pkg-builder/Dockerfile
Updating the container currently tries to remove a protected package.
Add --nobest so that the problematic packages are not updated.
> build/centos-stream-8/pkg-builder: add --nobest to update command

- build/centos-stream-8/guest-image/tdx-guest-stack.sh
- build/rhel-8/guest-image/create-efi-img.sh
- build/rhel-8/guest-image/tdx-guest-stack.sh
Correct EFI boot path to /boot/efi/EFI/redhat/ for rhel guest image
> guest-image: fix wrong path for rhel

- build/rhel-8/intel-mvp-spr-qemu-kvm/build.sh
- build/rhel-8/intel-mvp-spr-qemu-kvm/spr-qemu.spec
1. Obsoletes qemu-kvm-block-iscsi to avoid conflicts because it's not packaged
but some distros have the orignal package.
2. Disable qemu-kvm build test. Sometime the cases will fail on rhel like
qom-test, pxe-test and bios-tables-test... These tests need some patches to
run on rhel but could not be applied to current source. However it doesn't
impact the qemu functionality to support TDX, AMX.
> build: update spr qemu to SPR-BKC-QEMU-pub-v1

- build/centos-stream-8/build-repo.sh
- build/rhel-8/build-repo.sh
It is recommended that all commands be run in non-root,
except for dnf builddep in each build script.
> build: remove root command

- README.md
- build/centos-stream-8/README.md
- build/rhel-8/README.md
- build/centos-stream-8/README.md: Add description about stack build for CentOS stream 8
- build/rhel-8/README.md: Add description about stack build for RHEL 8
- README.md: Remove the section about "install from prebuilt"
> build/README.md: Add description about stack build for each distros

- README.md
1. TDX SEAM module is already opened source at https://github.com/intel/tdx-module/.
2. Add steps to install signed build TDX module.
3. Add reference to verify the TDX host.
> README.md: Add the TDX SEAM module

- build/centos-stream-8/intel-mvp-spr-qemu-kvm/build.sh
- build/centos-stream-8/intel-mvp-spr-qemu-kvm/spr-qemu.spec
> build/centos-stream-8/spr-qemu: move to tag SPR-BKC-QEMU-pub-v1

- utils/pycloudstack/pycloudstack/vmguest.py
- utils/pycloudstack/pycloudstack/vmm.py
- utils/pycloudstack/pycloudstack/vmparam.py
Originally, use CPUTopology for cores, threads, sockets and vcpus and memory
size for whole VM spec, it bring lots of parameter and overide relationship.
To simplify the design, create a new VMSpec = CPUTopoloy + memsize.
With this new design,
- MODEL_LARGE => VMSpec.model_large()
- MODEL_BASE  => VMSpec.model_base()
- MODEL_NUMA  => VMSpec.model_numa()
> vmparam.py: Use VMSpec replace CPUTopology and memory size

- build/centos-stream-8/build-repo.sh
- build/centos-stream-8/guest-image/tdx-guest-stack.sh
- build/rhel-8/build-repo.sh
When running build-repo.sh again, e.g. customize qemu and then rebuild repo,
most likely guest kernel packages have already been moved.
> build-repo: move guest kernel packages if they exist

- utils/pycloudstack/pycloudstack/templates/sgx-base.xml
- utils/pycloudstack/pycloudstack/virtxml.py
- utils/pycloudstack/pycloudstack/vmm.py
- utils/pycloudstack/pycloudstack/vmparam.py
1. sgx-base template cleanup
2. To fit latest SGX EPC Qemu command lines:
```xml
-object memory-backend-epc,id=mem1,size=64M,prealloc=on \
-object memory-backend-epc,id=mem2,size=28M \
-M sgx-epc.0.memdev=mem1,sgx-epc.0.node=0, \
sgx-epc.1.memdev=mem2,sgx-epc.1.node=1
```
add function `set_epc_params` and class `SGXVMSpec` to customize config for each VM
usage:
```python
epc = [{'size': '32G', 'prealloc': True, 'node': 0}]
Spec = SGXVMSpec(sockets=1, cores=8, threads=1, memsize=(64 * 1024 * 1024), epc=epc)
```
Signed-off-by: Dong Xiaocheng <xiaocheng.dong@intel.com>
> utils/pycloudstack: update and customize SGX EPC config for each VM

- utils/pycloudstack/pycloudstack/vmguest.py
- utils/pycloudstack/pycloudstack/vmm.py
1. Support specific mode in libvirt shutdown. It supports mode "default"/"acpi"/"agent" for now.
2. Catch exception of DomainUUID cannot be found if the VM has been explicitly destroyed before teardown.
> vmguest.py and vmm.py - support virsh shutdown mode

- utils/pycloudstack/pycloudstack/templates/legacy-base.xml
- utils/pycloudstack/pycloudstack/templates/ovmf-base.xml
- utils/pycloudstack/pycloudstack/templates/tdx-base.xml
- utils/pycloudstack/pycloudstack/virtxml.py
- utils/pycloudstack/pycloudstack/vmguest.py
- utils/pycloudstack/pycloudstack/vmm.py
- utils/pycloudstack/pycloudstack/vmparam.py
With this commit, it can collect VM boot console log for debug purpose. VM log will be kept for unhealthy VMs.
1. virtxml.py - add methods to parse and set logfile
2. vmguest.py - add method to delete vm log file, keep log file for unhealthy VM
3. vmm.py - add method to delete vm log file
4. vmparam.py - add kernel cmdline to catch kernel log
5. update VM xml template to generate VM log
> Add console log for VMs

- .gitignore
These paths can not be removed with `git clean -dfx` as they contain `.git`
> ignore build paths with .git

- start-qemu.sh
When using vsock to get TDREPORT, passing "tdx_disable_filter" on the kernel
command line used to be required as a workaround. However, this workaround also
compromised the security.
Disabling the filter is no longer needed for recent kernels.
Vsock driver has been audited and added to the list of allowed TDX devices.
> start-qemu.sh: remove "tdx_disable_filter" requirement

- utils/pycloudstack/pycloudstack/vmparam.py
In sometimes, need append new field into kernel command line, before
the field, a blank char should be added to split the different fields.
This patch will append a blank char for each new field.
> vmparam: Add blank char for any new field appending to kernel command

- doc/secure_boot.md
The previous download link is not available.
Change to new link that redirects the download to one of its mirrors.
> doc/secure_boot.md: update link for sbsigntools-0.9.4-2.fc33.x86_64.rpm

- build/ubuntu-22.04/intel-mvp-tdx-guest-grub2/debian/changelog
- build/ubuntu-22.04/intel-mvp-tdx-guest-grub2/debian/control
grub-efi-amd64-bin and grub-efi-amd64 will install grubx64.efi in ESP
> ubuntu 22.04: build unsigned grub packages

- build/ubuntu-22.04/intel-mvp-tdx-guest-shim/debian/shim.postinst
There is no /dev/disk/by-id in guest VM using virtio-blk driver. Error message:
Unknown device "/dev/disk/by-id/*": No such file or directory
> ubuntu 22.04: fix shim postinstall error in guest VM using virtio-blk

- build/ubuntu-22.04/intel-mvp-spr-kernel/build.sh
- build/ubuntu-22.04/intel-mvp-spr-kernel/debian.master/changelog
- build/ubuntu-22.04/intel-mvp-spr-kernel/debian/changelog
> ubuntu 22.04: update kernel to SPR-BKC-PC-v8.5

- utils/pycloudstack/pycloudstack/templates/sgx-base.xml
Without this line, SGX VM cannot be created successfully
> sgx-base.xml: Add log file to template

- build/ubuntu-22.04/intel-mvp-spr-kernel/build.sh
- build/ubuntu-22.04/intel-mvp-spr-kernel/debian.master/changelog
- build/ubuntu-22.04/intel-mvp-spr-kernel/debian/changelog
- build/ubuntu-22.04/intel-mvp-spr-kernel/patches/0001-X86-VIRTEXT-Fix-false-alarm-of-vmptrst-failure-in-ra.patch
- build/ubuntu-22.04/intel-mvp-spr-kernel/patches/0001-efi-x86-stub-fix-absolute-symbol-reference.patch
- build/ubuntu-22.04/intel-mvp-spr-kernel/patches/0001-x86-MM-Use-pgprot_cc_guest-in-__ioremap_caller-for-T.patch
- build/ubuntu-22.04/intel-mvp-spr-kernel/patches/series
Add 2 patches:
1. fix build error in SPR-BKC-PC-v8.8
2. fix kernel panic when enable TDX
> ubuntu 22.04: update to SPR-BKC-PC-v8.8

- utils/pycloudstack/pycloudstack/vmguest.py
removeall will call remove to delete VM, including VM image and VM log
> vmguest.py: refactor methods removeall and remove for vm deletion

- start-qemu.sh
Remap CTRL-C functionality to CTRL-] while in QEMU.
This allows using CTRL-C within QEMU without exiting QEMU.
In case we need to terminate QEMU, we can use CTRL-] instead.
Upon QEMU termination the CTRL-C functionality is restored.
> start-qemu.sh: allow using CTRL-C in QEMU

- start-qemu.sh
Adjust start-qemu.sh so that both CentOS Stream and Ubuntu are supported
> start-qemu.sh: Support Ubuntu

- utils/pycloudstack/pycloudstack/dut.py
- utils/pycloudstack/pycloudstack/templates/legacy-base.xml
- utils/pycloudstack/pycloudstack/templates/ovmf-base.xml
- utils/pycloudstack/pycloudstack/templates/sgx-base.xml
- utils/pycloudstack/pycloudstack/templates/tdx-base.xml
- utils/pycloudstack/pycloudstack/virtxml.py
- utils/pycloudstack/pycloudstack/vmguest.py
- utils/pycloudstack/pycloudstack/vmm.py
- utils/pycloudstack/pycloudstack/vmparam.py
1. Update qemu in xml template so that it reflects to corresponding distro qemu
2. Update vmguest.py to judge guest image distro and set corresponding rootfs to kernel command line based on distro.
3. Update virtxml.py to support qemu from different distro
4. Update vmm.py to judge host distro and set corresponding qemu and seabios information based on distro.
> Update libvirt template and code to support multiple distro

- .github/workflows/pr-ubuntu-22.04-qemu.yml
- build/ubuntu-22.04/intel-mvp-spr-qemu/build.sh
mk-build-deps failed to install some dependencies on ubuntu 22.04 VM.
> ubuntu 22.04: install unmet build dependencies for qemu build

- build/ubuntu-22.04/build-repo.sh
- build/ubuntu-22.04/guest-image/tdx-guest-stack.sh
Build TDX kernel, qemu, tdvf, libvirt debian packages in host_repo
host_repo is not an ubuntu repository list. You can install the debian packages directly.
> ubuntu 22.04: build host repo in build-repo.sh

- doc/tdx_libvirt_direct.ubuntu.xml.template
- doc/tdx_libvirt_grub.ubuntu.xml.template
- doc/tdx_libvirt_grub.xml.template
new templates for Ubuntu:
doc/tdx_libvirt_direct.ubuntu.xml.template
doc/tdx_libvirt_grub.ubuntu.xml.template
updated (removed -shstk requirement)
doc/tdx_libvirt_direct.xml.template
doc/tdx_libvirt_grub.xml.template
> update templates for virsh

- build/ubuntu-22.04/build-repo.sh
- build/ubuntu-22.04/intel-mvp-spr-kernel/build.sh
- build/ubuntu-22.04/intel-mvp-spr-kernel/debian/rules.d/2-binary-arch.mk
1. Set non-interactive installation for all build dependencies.
2. Disable DKMS build for zfs and v4l2loopback to simplify the script.  They are not loaded in kernel by default
> ubuntu 22.04: optimize build process for automation

- utils/pytdxmeasure/pytdxmeasure/actor.py
- utils/pytdxmeasure/pytdxmeasure/ccel.py
- utils/pytdxmeasure/pytdxmeasure/cli.py
New ACPI device changed to /sys/firmware/acpi/tables/CCEL
Add 2 fields in event log, CC type and CC subtype.
Please refer to section 4.3.3 CC-Event Log in GHCI specification for TDX 1.5
> pytdxmeasure: update to new confidential computing measurement protocol

- build/centos-stream-8/intel-mvp-spr-qemu-kvm/spr-qemu.spec
Avoid qemu check error on some build environments.
> qemu-kvm: disable build check for c8s

- utils/pycloudstack/pycloudstack/vmguest.py
- utils/pycloudstack/pycloudstack/vmparam.py
I noticed rootfs is added to kernel cmdline each time a new VM is created, which makes the parameter repeat. When there is already rootfs in kernel cmdline, do not add it one more time.
> vmguest.py - fix issue that rootfs being added multiple times

- build/ubuntu-22.04/guest-image/tdx-guest-stack.sh
Ubuntu: "virt-customize" is provided by "libguestfs-tools" package.
There does not seem to be "libguestfs-tools-c" package.
> tdx-guest-stack.sh: fix error message

- build/ubuntu-22.04/build-repo.sh
There is a package conflict, grub cannot be built with libzfslinux-dev installed.
However, libzfslinux-dev is required for other package(s) so at some point
the package will be installed.
Fix the conflict by uninistalling libzfslinux-dev before building grub.
> ubuntu/build-repo.sh: fix dependency conflict

- build/ubuntu-22.04/guest-image/tdx-guest-stack.sh
Mask pollinate.service to reduce the boot time.
Some workloads and tests require more space.
> ubuntu: mask pollinate.service and scale disk size to 20G

- build/ubuntu-22.04/guest-image/tdx-guest-stack.sh
- doc/secure_boot.md
- start-qemu.sh
start-qemu.sh: fix KERNEL_CMD_NON_TD being overwritten when appending root partition
tdx-guest-stack.sh: remove installation of unused package for ubuntu guest
secure_boot.md: fix typo tdvf-key-enroll to tdvfkeyenroll
> refine start-qemu.sh, tdx-guest-stack.sh and secure_boot.md

- doc/run_tests.md
In a brand new environment, gcc and gcc-c++ are also required to setup test environment
Signed-off-by: Hao,Ruomeng <ruomeng.hao@intel.com>
> doc/run_tests.md: add required packages for tests running

- build/centos-stream-8/intel-mvp-tdx-tdvf/build.sh
- build/centos-stream-8/intel-mvp-tdx-tdvf/tdvf.spec
- build/rhel-8/intel-mvp-tdx-tdvf/build.sh
- build/rhel-8/intel-mvp-tdx-tdvf/tdvf.spec
- build/ubuntu-22.04/intel-mvp-tdx-tdvf/build.sh
- build/ubuntu-22.04/intel-mvp-tdx-tdvf/debian/changelog
- build/ubuntu-22.04/intel-mvp-tdx-tdvf/debian/rules
Use default submodule url for cmocka.
> build: update tdvf to 2022-tdvf-ww39.4

- build/ubuntu-22.04/build-repo.sh
Ubuntu qemu build path is changed to intel-mvp-tdx-qemu-kvm same as RHEL.
> build: fix wrong path in build-repo.sh for Ubuntu

- .github/workflows/pr-test-build-centos-stream-8-kernel.yml
- .github/workflows/pr-test-build-centos-stream-8.yml
- .github/workflows/pr-ubuntu-22.04-qemu.yml
- .github/workflows/pr-ubuntu-22.04-shim.yml
- .github/workflows/pr-ubuntu-22.04-tdvf.yml
- build/ubuntu-22.04/intel-mvp-tdx-tdvf/debian/patches/series
Add github workflow to check ubuntu tdvf PR.
Fix ubuntu tdvf build error.
> build: add tdvf build check for ubuntu 22.04

- start-qemu.sh
Although SGX is not supported in TD VMs, SGX functionality can be enabled in non-TD VMs. However, non-TD VMs do not support SGX by default. In order to enable SGX in VMs, QEMU needs to launch VMs with some additional SGX specific arguments, see:
https://www.qemu.org/docs/master/system/i386/sgx.html
This patch implements SGX support by defining a new type of VM: "sgx".
Examples:
./start-qemu.sh -i <image> -b grub -t sgx
./start-qemu.sh -i <image> -b grub -s -t sgx
./start-qemu.sh -i <image> -b grub -s -t sgx -c 8
./start-qemu.sh -i <image> -k <kernel> -t sgx
> start-qemu.sh: add support for VMs with SGX

- utils/pycloudstack/pycloudstack/virtxml.py
Running the regression suit of tests:
sudo ./run.sh -s regression
typically results in several tests failing with an error such as:
text = 16777216.0
...
TypeError: argument of type 'float' is not iterable
This patch detects attempts setting memory field in XML using 'float'. The 'float' value is first converted to 'int' using 'round' to eliminate decimal values and then the 'int' value is converted to a string.
> pycloudstack/virtxml.py: memory.setter: handle float instance

- tests/tests/test_tdx_host_status.py
This test case is not applicable in kernel 5.19 anymore. Remove the test case.
> test_tdx_host_status.py: remove tdx cpuinfo test case

- build.sh
> build.sh: fix the shell check issue by adding double quote

- utils/pycloudstack/pycloudstack/vmguest.py
Expose cpu_ids to VMGuestFactory, which helps to bind cpus when use VMGuestFactory to create VMs.
Signed-off-by: Zhou,Lei <lei.zhou@intel.com>
> vmguest: expose cpu_ids to VMGuestFactory

- tests/tests/test_tdvm_tsc.py
- tests/tests/test_tdx_guest_status.py
- utils/ovmfkeyenroll/ovmfkeyenroll/var_enroll.py
1. Use cpu flags to varify TDX initilization in TD guest other than checking keyword in messages.
2. Fix incorrect usage of finding a sub-string.
> Tests: fix test issue

- utils/pycloudstack/pycloudstack/vmguest.py
- utils/pycloudstack/pycloudstack/vmparam.py
Introduce the migtd params and the path to migtd.bin. Create a static-method for migtd spec.
- add migtd_pid and incoming_port these two params for migratable TD.
- Cuz srcTD and dstTD need same image, now vmfactory will not clone image for migratable TD.
> Introduce new and necessary params for live-migration

- utils/pycloudstack/pycloudstack/templates/tdx-base-perf.xml
This is to adapt for kernel 6.2 usage change about memfd. Corresponding
change is already adopted in template for functional test (tdx-base.xml).
The change here is used for performance test.
> templates/tdx-base-perf.xml: add memoryBacking using memfd

- utils/pycloudstack/pycloudstack/vmguest.py
Increase the timeout for wait_for_state from 20s to 30s to
avoid some false alarm in functional tests which are caused
by insufficient timeout.
> vmguest.py: give longer timeout to wait_for_state

- utils/pycloudstack/pycloudstack/vmguest.py
As suggestion from reviewers, the timeout value could be set
case by case. So revert previous change that has global impact.
> vmguest.py: revert previous global timeout change

- attestation/pytdxmeasure/requirements.txt
- tests/requirements.txt
As a recommended best known practice, using the latest version
for some dependencies to avoid some known issues.
> python requirements.txt: use latest dependencies

- utils/td-migration/README.md
- utils/td-migration/connect.sh
- utils/td-migration/destTD.sh
- utils/td-migration/mig-flow.sh
- utils/td-migration/migTD_dst.sh
- utils/td-migration/migTD_src.sh
- utils/td-migration/pre-mig.sh
- utils/td-migration/sourceTD.sh
1. Add the td-migration doc for customers who could follow the single or cross host td-migration test steps to verify its basic function
2. Develop some td-migration required test scripts to simplify its usage.
Signed-off-by: Zhou, Lei <lei.zhou@intel.com>
> Initial td-migration document and test scripts

- attestation/pytdxmeasure/examples/extend_ima.py
* create example-usage folder to contain all example usage of pytdxmeasure utilities
* add script to utilize RTMR extend utility for IMA measurements
> Pytdxmeasure: Add example usage for RTMR extend

- start-qemu.sh
Current default root partition is vda1 instead of vda3.
> start-qemu.sh: set vda1 the default root partition

- tests/tests/test_tdvm_network.py
Change VM type from legacy to TD
> tests/test_tdvm_network.py: Fix typo in test

- start-qemu.sh
This PR fix [issue#289](https://github.com/intel/tdx-tools/issues/289)
It's better to append the option of `mac` after options of `-device virtio-net-pci,netdev=mynet0`
> Fix bug for launching TD VM with custom VM MAC address via start-qemu.sh

- attestation/pytdxmeasure/README.md
- attestation/pytdxmeasure/examples/extend_ima.py
- attestation/pytdxmeasure/pytdxmeasure/cli.py
- attestation/pytdxmeasure/pytdxmeasure/rtmr.py
- attestation/pytdxmeasure/tdx_extend_rtmr
* Provide 3 types of data input for rtmr extend 
* extend with any length string(will be converted to sha384 digest automatically) 
* extend with sha384 digest
* extend with raw data(must be 48B length)
* Add extra readme for rtmr extend
> Add more option for user to use rtmr extend

- start-qemu.sh
This PR fix [issue#291](https://github.com/intel/tdx-tools/issues/291) via Qemu options: `net` and `dhcpstart`.
There is existing TD VM at `10026` in the bare-metal, then I launched another TD VM in `10029` by changing the `start-qemu.sh`, and executed the command `./start-qemu.sh -i td-guest-ubuntu-22.04.qcow2 -k vmlinuz -r /dev/vda1 -m 52:54:98:76:54:32 -a 10.0.2.18` based on this PR. 
Note: Make sure that the [issue#289](https://github.com/intel/tdx-tools/issues/289) should be fixed at first.
The below output shows that I have 2 TD VMs now:
One VM with IP is `10.0.2.15` and Mac is `52:54:00:12:34:56`
Another VM with IP is `10.0.2.18` and Mac is `52:54:98:76:54:32`
> Support custom ip address for TD VMs with network cidr and dhcp start address

- utils/pycloudstack/pycloudstack/vmm.py
No need to generate temp OVMF for each TDVM.
> Remove temp OVMF generation

- utils/pycloudstack/pycloudstack/vmguest.py
Add new parameter to control the check interval for wait_for_ssh_ready.
The default value is 1 (second). Callers can customize this value as their need.
e.g. some benchmark needs more frequent check.
> vmguest.py: add check interval parameter

- start-qemu.sh
* Add an extra option in start-qemu.sh for extra kernel cmdline needed in vm boot
> start-qemu.sh: add new option for kernel cmdline

- .github/workflows/.aspell.en.pws
- build/rhel-8/README.md
- build/ubuntu-22.04/README.md
Add build requirements that need to be installed on RHEL. 
Add special note for commercial RHEL.
Add a hint to build separately using build.sh .
Simplify one heading level in README for Ubuntu.
> build: refactor README for build on RHEL and Ubuntu

- utils/td-migration/mig-td.sh
- utils/td-migration/user-td.sh
Just some adjustment for the memory parameters change of qemu.
Using /dev/shm to access the whole memory.
> td-migration: adjust qemu parameters for memory

- utils/td-migration/connect.sh
Without this wait time, we could get error like this when connect:
socat[24288] E connect(5, AF=2 127.0.0.1:9009, 16): Connection refused
> td-migration/connect.sh: wait 3s before connect

- utils/td-migration/mig-flow.sh
- utils/td-migration/pre-mig.sh
For some version of nc, the default is no timeout that will hang the execution of of script.
Adding 3 seconds timeout can resolve this.
> td-migration: add timeout for nc

- start-qemu.sh
It is not accurate to use the suffix string of file name to judge whether image's format is qcow2 or raw. For example, Ubuntu's cloud image is ending with .img, but its format is qcow2.
So change to use `file` command to check the image format.
> start-qemu.sh: use file command to judge the image format

- .pylintrc
- utils/pycloudstack/pycloudstack/virtxml.py
- utils/pycloudstack/pycloudstack/vmguest.py
- utils/pycloudstack/pycloudstack/vmm.py
- utils/pycloudstack/pycloudstack/vmparam.py
1. vmguest.py: parameters are added to indicate whether a vTPM TD needs to be created along with TD
2. vmparam.py: Add vTPM TDVF binary path and vTPM TD binary path
3. vmm.py: update destroy method so that a VM can be destroyed but not undefined
4. virtxml.py: Add method to set vtpm fields in libvirt xml template
> pycloudstack: update framework to support vtpm

- build/rhel-8/build-repo.sh
- build/ubuntu-22.04/build-repo.sh
The script redirects each build log, set pipefail to return the status of build.sh.
> build: set pipefail in build-repo.sh

- build/rhel-8/intel-mvp-tdx-migration/build.sh
- build/rhel-8/intel-mvp-tdx-migration/tdx-migration.spec
- build/ubuntu-22.04/intel-mvp-tdx-migration/build.sh
- build/ubuntu-22.04/intel-mvp-tdx-migration/debian/changelog
- build/ubuntu-22.04/intel-mvp-tdx-migration/debian/rules
Add /usr/share/td-migration/migtd.servtd_info_hash.
> migtd: update to v0.2.3

- tests/run.sh
1. Set the default guest OS from "rhel" => "ubuntu"
2. Add more description about the "-g" option for all potential OS distro types
3. Add step to detect the VM ssh key, if not exists, then generate one
> tests/run.sh: Refine the test launch script

- build/ubuntu-22.04/pkg-builder
Add argument --shell to allow getting access to shell inside the docker container
It is useful for incremental and customized build
> Enhance pkg-builder script

- build/ubuntu-22.04/intel-mvp-tdx-kernel/build.sh
- build/ubuntu-22.04/intel-mvp-tdx-kernel/debian.master/control.stub.in
- build/ubuntu-22.04/intel-mvp-tdx-kernel/debian/control
Fix "Load BTF from vmlinux: Invalid argument" caused by Ubuntu distro pahole update.
> kernel: limit pahole version

- build/ubuntu-22.04/intel-mvp-tdx-kernel/build.sh
Allow the automatic downgrade of pahole during the installation, to also fix the "Load BTF from vmlinux: Invalid argument" issue on systems with an already newer pahole version.
> kernel: allow pahole installation to downgrade version

- utils/pycloudstack/pycloudstack/virtxml.py
- utils/pycloudstack/pycloudstack/vmguest.py
- utils/pycloudstack/pycloudstack/vmm.py
1. UPM 2M huegpage require to specify a hugepage_path. Modify pycloudstack framework to add the parameter.
2. Fix a issue in bind_cpuids - keep cpu_ids list to make sure the list is consistent in cycling test.
> pycloudstack: Support UPM 2M hugepage usage

- utils/check-tdx-host.sh
The kernel module msr is needed for rdmsr command, try to load it at the beginning
of the script
> Fix script check-tdx-host.sh

- build/ubuntu-22.04/pkg-builder
Add argument --shell to allow getting access to shell inside the docker container It is useful for incremental and customized build
Support building guest packages separately.
> Enhance pkg-builder script (#425)

- build/ubuntu-22.04/README.md
- build/ubuntu-22.04/guest-image/README.md
No need to install them. Distro grub and shim already support TDX measurement.
> ubuntu 22.04: remove TDX grub and shim from guest image README

- utils/pycloudstack/pycloudstack/vmguest.py
This parameter is only used by the TDVMs created by VMMQemu, not suitable for VMMLibvirt.
> vmguest.py: support set up mac address

- utils/pycloudstack/pycloudstack/virtxml.py
- utils/pycloudstack/pycloudstack/vmguest.py
- utils/pycloudstack/pycloudstack/vmm.py
This change is for network performance test. User can set driver name other than using default vhost-net. 
1. virtxml.py: support to find an element via attribute value, and set driver name 
2. vmm.py: support to set driver name in xml template when it's specified 
3. vmguest.py: support to set driver when creating VM
> pycloudstack: Support to set driver name for performance test

- build/ubuntu-22.04/intel-mvp-tdx-kernel/build.sh
Allow the automatic downgrade of pahole during the installation, to also fix the "Load BTF from vmlinux: Invalid argument" issue on systems with an already newer pahole version.
> kernel: allow pahole installation to downgrade version (#435)

- utils/pycloudstack/pycloudstack/vmguest.py
- utils/pycloudstack/pycloudstack/vmm.py
Method set_mem_numa is used to bind with cpuids which is not necessary. Whether to set_mem_numa should depend on the value of vminst.mem_numa which is set when VM is created.
> pycloudstack: Only set numa in xml when it's set when VM is created

- build/ubuntu-22.04/build-vmware-td.sh
Enable TDX Guest grub2 build for vmware TD.
> vmware: Add TDX guest grub2 build instructions

- doc/tdx_libvirt_direct.ubuntu_host.xml.template
- doc/tdx_libvirt_direct.xml.template
- doc/tdx_libvirt_grub.ubuntu_host.xml.template
- doc/tdx_libvirt_grub.xml.template
- utils/pycloudstack/pycloudstack/templates/tdx-base-perf.xml
- utils/pycloudstack/pycloudstack/templates/tdx-base.xml
1. Update pycloudstack xml template for TD to turn off debug by default
2. Update xml templates in doci to turn off debug by default
> Update TD security launch policy to turn off debug

- utils/pycloudstack/pycloudstack/vmguest.py
- utils/pycloudstack/pycloudstack/vmm.py
- utils/pycloudstack/pycloudstack/vmparam.py
1. Single OVMF binary for either with vTPM or not
2. Fix kernel cmdline cannot be passed to xml issue introduced by vmm early initialization
> pycloudstack: Update vTPM

- utils/ovmfkeyenroll/ovmfkeyenroll/secure_boot.py
- utils/ovmfkeyenroll/ovmfkeyenroll/var_enroll.py
- utils/ovmfkeyenroll/pyproject.toml
- Add ovmfvarenroll tool to enroll normal variables to OVMF.
- Update ovmfkeyenroll parameters PK/KEK/db/dbx to optional, making the usage more flexible.
> utils/ovmfkeyenroll: add ovmfvarenroll and update key parameters

- .github/workflows/.aspell.en.pws
- utils/td-migration/README.md
- utils/td-migration/mig-td.sh
- utils/td-migration/pre-mig.sh
Normally, MigTD use vsock as the default way to do pre-migration.
Now, add the virtio-serial support as an alternative way.
> td-migration: support virtio-serial for MigTD

- tests/README.md
net-tools provides `arp` command used by the test suite (pycloudstack/vmm.py) to find the IP of VMs.
The lack of `arp` causes failures in the test execution.
> Tests: Add net-tools to the required package list

- start-qemu.sh
Replace confidential-guest-support=tdx with memory-encryption=tdx.
Refer to https://sigs.centos.org/virt/tdx/guest/#with-qemu
> start-qemu.sh: use memory-encryption=tdx in QEMU cmdline for TDX guest

- utils/ovmfkeyenroll/ovmfkeyenroll/var_enroll.py
The type of firmwarevolume attributes is uint32 not uint8
```c
typedef UINT32 EFI_FVB_ATTRIBUTES_2;
```
> fix the typo of firmwarevolume in comments
